### ISSUE TITLE
Mask not properly drawing or clearing

### ISSUE THREAD

**Issue by Heikin-Ashi** [bobcamera/bobcamera#130]
**Copied from Discord**
I got it working on my Dahua PTZ using the same admin/ONVIF user setup as my fisheye. I'm having a bit of trouble getting the mask to draw properly or delete properly. The screen shot above shows an attempt draw a rectangle over the entire screen. For some reason it's splitting the mask diagonally. It also doesn't seem to clear properly. When I hit the "clear mask" button to clear any drawings and then "send mask as ROS2 message button", I get a completely masked screen. I'm finding it difficult to get rid of a mask once something has been imputed. Also, we should probably give the user a hint about how the mask functions. Knowing that the enclosed polygon of the mask will represent the area that will be visible to the camera and not the area excluded from the camera would probably be helpful.

![image](https://github.com/bobcamera/bobcamera/assets/86312516/9128b52c-c549-45da-828f-a784995b3b38)

**Copied from Discord**
Stopping and the restarting the container and relaunching the web UI seems to have fixed it. Well, at least the clearing the mask part. I didn't delete the .jpg, .png, or .svg. Just did a restart.

![image](https://github.com/bobcamera/bobcamera/assets/86312516/ef7e131c-8d60-48ec-ab80-902dad23d615)

**Comment by Micky-G** [comment]
I have added the ability to delete a mask now, maybe when we do a new release you could try again please?
