### ISSUE TITLE
[BUG] Detection Mask Creation in Web GUI doesn't seem to work.

### ISSUE THREAD

**Issue by danlohman** [bobcamera/bobcamera#145]
**Describe the bug**
After creating a detection mask and saving it in the web GUI, there is an alert message that states it may take 60 seconds for the mask to be applied.  When I navigate back to the live view of the feed, there is no change even after 13 minutes.  

**Expected behavior**
I'd expect the detection mask to be applied within 60 seconds and for the detections within the masked region to stop at that time.   Id also expect some type of indication that the mask is applied and working and where it is blocking detections. 

**Desktop (please complete the following information):**
Windows 10 Desktop
Running WSL

**Comment by Micky-G** [comment]
@danlohman the detection mask is only visible on the detection mask creation page. The idea behind it is that you want to mask out portions of the image stream that is excluded from detection but still visible for viewing. The privacy mask is the mask that you use to mask out sections from a privacy standpoint and is visible on the live stream.
