### ISSUE TITLE
User wants ability to choose not to install rStudio

### ISSUE THREAD

**Issue by danlohman** [bobcamera/bobcamera#149]
- User wants ability to choose not to install rStudio. 
- It's large and unless I'm unaware of something its required for, my thought is that we don't include it by default.
- If a user wants to choose to include it, there could be an option to select for that.

**Comment by Micky-G** [comment]
@danlohman that is a fair point, we should be able to support that, thanks for the suggestion.

**Comment by Micky-G** [comment]
@danlohman this will be fixed in the next release dude.

**Comment by Micky-G** [comment]
This has been fixed, we have a docker compose yaml file that excludes rstudio.
