### ISSUE TITLE
[BUG] Windows Setup Instructions Clarification

### ISSUE THREAD

**Issue by danlohman** [bobcamera/bobcamera#151]
When installing for Windows (WSL) we can clarify the process a bit (the process seems to differ based on some early conditions)

- The order and source of the Ubuntu install affects what the steps are to installing WSL.  Getting Ubuntu from the Microsoft store resulted in the steps in the Windows setup document being a bit off.  We might want to somehow make a note of that and/or recommend a specific Ubuntu source. 
- Have the user check to see what version WSL they are running before having them attempt to change to version 2
- Have the user check if virtualization is available on their PC
- Have the user check if virtualization is enabled on their PC

**Comment by jdmaudio** [comment]
I think this can be closed following the updates here https://github.com/bobcamera/bobinstall/pull/1
