### ISSUE TITLE
Ros2 launch files (launch_application.sh & .env)

### ISSUE THREAD

**Issue by danlohman** [bobcamera/bobcamera#181]
- Should we remove the .env.example file in the ros2 folder.  I don't think a .env file is used at the ros2 container level. It seems as though the variables are only able to be defined in the just launch_application.sh when launching a container from the ros2 directory. 

- The RTSP variables in the launch_application.sh in the ros2 directory should also include the Height, Width, and FPS.  This allows a user a way to configure the RTSP camera if Onvif settings are not detected.  The default height and width are set to 0 which could probably be changed to positive values. 

I could very possibly be missing something on the above.

**Comment by fcbarros** [comment]
This is resolved on the newer yaml files, no more environment variables.
