### ISSUE TITLE
Topic without single quotes in app_config.yaml 

### ISSUE THREAD

**Issue by danlohman** [bobcamera/bobcamera#184]
Looks like there is a typo in the camera_info_topic topic in the app_config.yaml file.
No single quotes around the topic name. 

allsky_recorder_node:
  ros__parameters:
    recordings_directory: 'assets/recordings'
    img_topic: 'bob/frames/allsky/masked/privacy'
    fg_img_topic: 'bob/frames/foreground_mask'
    tracking_topic: 'bob/tracker/tracking'
    camera_info_topic: bob/camera/all_sky/camera_info

**Comment by fcbarros** [comment]
This is fixed on newer versions.
