### ISSUE TITLE
[BUG] Integrated webcam not working

### ISSUE THREAD

**Issue by djtarki** [bobcamera/bobcamera#188]
**Describe the bug**
I've installed the latest version and run it succesfully on Ubuntu 24.04 using the video samples included. When I choose to use the USB camera as source (configured as 0) it won't load. The camera works fine with Cheese for instance (https://snapcraft.io/cheese)

**To Reproduce**
1. ./config.sh to configure the source type 2 (usb) and USB source selection '0'
2. ./run.sh with default option (d)
3.  The service will launch but with empty images (screenshot attached).

Attached logs captured to show kernel version, camera information and bobcamera output when running:

[CameraSpecs.txt](https://github.com/bobcamera/bobcamera/files/15261504/CameraSpecs.txt)
[kernel_version.txt](https://github.com/bobcamera/bobcamera/files/15261505/kernel_version.txt)
[run_output.txt](https://github.com/bobcamera/bobcamera/files/15261506/run_output.txt)

**Desktop (please complete the following information):**
 - Ubuntu 24.04 Desktop 64
 - Firefox (but this is not the problem since in the logs it can be seen the problem is GStreamer and OpenCV accesing the camera)
 - Asus Zenbook --> https://www.pcmag.com/reviews/asus-zenbook-14-oled-um3402

**Additional context**
Love this! Keep the good work!

**Comment by Micky-G** [comment]
Hi @djtarki thanks for the feedback. I actually wrote up a [wiki page](https://github.com/bobcamera/bobinstall/wiki/Will-BOB-work-with-a-USB-camera%3F) on this yesterday as you will need to make a change to the docker compose file to pass through the camera device into the container. Would you mind giving it a go and letting us know what you think please?

**Comment by djtarki** [comment]
Thanks a lot Micky for answering so fast! I've followed the [wiki page](https://github.com/bobcamera/bobinstall/wiki/Will-BOB-work-with-a-USB-camera%3F)  and now the camera starts and I can see the images when going to http://localhost:8080/

The only thing I noticed is that the frame rate is quite poor (barely 5fps --> 
![Screenshot from 2024-05-09 21-10-04](https://github.com/bobcamera/bobcamera/assets/167533819/41b37d79-8f76-4efe-8a2f-f55feb126873)
). Is that normal? (maybe it is due to the processing required)

Thanks again!

**Comment by Micky-G** [comment]
Hi @djtarki, well done for getting it working! Yes so that will be down to your camera, all I can say is that, that is about as much as I get from my usb camera at its highest resolution.

Once you happy, would you mind closing the issue.

**Comment by djtarki** [comment]
Thanks Micky for clarifying.  I hope, the performance can eventually get better as part of the roadmap! Reason? **High-res (4k!) High-speed (120 fps!)** cameras are required to really analyse objects that are far in the skies...  Thanks for all the good work. At your service if want to discuss.

![image](https://github.com/bobcamera/bobcamera/assets/167533819/dc25018b-e644-4ab5-aca3-b42f25e659cf)

**Comment by djtarki** [comment]
Closing as it is fixed.

**Comment by Micky-G** [comment]
@djtarki thanks mate appreciate the kind words. We will try and squeeze as much out of it as we can. 4k @ 120 fps on current hardware might be a stretch but we will see what we can do. 4k = about 8 MB depending on compression/no compression etc so that is about 960 MB / s using no compression. That will pretty much require a 10gig network connection. What sort of camera are you using for 4k @ 120 fps? That is some crazy hardware!

**Comment by djtarki** [comment]
I don't have such hardware (yet!) but there are plenty out there that can be even connected by USB (e.g. [example1](https://www.e-consystems.com/industrial-cameras/ar0234-usb3-global-shutter-camera.asp), [example2](https://www.amazon.com/ELP-Embedded-100degree-Distortion-Raspberry/dp/B0BHWHMPKH)... --> Delete if not allowed to share this type of links). 

More importantly, being a UFO nerd, for me it is clear that high-res / high-speed is needed. If you don't trust me (normal), have a look to [this video of Courtney Brown](https://youtu.be/gM9f3-AAoV8?si=Ox4cO2YaLdq_dQNH) where he explains why less is not enough and show some samples that are worth watching.

**Comment by Micky-G** [comment]
No I trust you mate, a group of us have been working on this tracker for a good couple of years now. We have tested many scenes and I completely agree with you, its just been a challenge to get the high throughput through the pipeline. Appreciate your input.
