### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CobraXLazer** [bobcamera/bobcamera#202]
Hello

Have installed the the new yaml setup, trying to start bobcamera with fresh install and it complaining about this!

bob-1  | Error loading YAML file: [Errno 21] Is a directory: 'assets/config/app_config.yaml'
bob-1  | [ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught multiple exceptions when trying to load file of format [py]:
bob-1  |  - RuntimeError: Failed to load YAML configuration
bob-1  |  - InvalidFrontendLaunchFileError: The launch file may have a syntax error, or its format is unknown
bob-1 exited with code 1                                                                                           

The CP command in the run file does not lock right.

**Comment by CobraXLazer** [comment]
I was a noob,

Maybe you should add info for the run section, 

"./run.sh my_config.yaml "

**Comment by fcbarros** [comment]
We will, the YAML version is not the official one yet, we are in testing phase and we will add more documentation.
