### ISSUE TITLE
Multi Camera Support ETA

### ISSUE THREAD

**Issue by lirexxx** [bobcamera/bobcamera#215]
Hi, thank you for the great software! Installed it today and it's running great.I do need a better quality camera.. 

To the question.. What is the ETA ot the Multi Camera Support feature?

In the meantime is there a way to run a second instance of BOB on the same computer, which can create a new docker package, be connected to another camera, and have web GUI on another port?

Can it be done as a workaround while the main multi cam feature is developed?

**Comment by Micky-G** [comment]
Hi @lirexxx we are getting reasonable close to being able to support this mode of operation. As you can appreciate, the first thing that we need to do is ensure that the whole detection and tracking pipeline is running as efficiently as possible. This then allows you to get the max out of your compute resource. The pipeline as been rewritten with this in mind, this solves other problems like frame skipping etc. as well. We are still working through some bugs and also trying to incorporate some GPU offloading to improve the processing pipeline even more. We unfortunately can't give an exact ETA but rest assured that we are working towards as quickly as we can.

**Comment by lirexxx** [comment]
Hi @Micky-G and thank you for the update! I guess I'll have to wait. :) I've already got 4 great cameras so three will be on standby until the multi-camera support update.

**Comment by Micky-G** [comment]
@lirexxx thanks very much for understanding, and we really appreciate the support!

**Comment by lirexxx** [comment]
> @lirexxx thanks very much for understanding, and we really appreciate the support!

Hey @Micky-G, I'm running the latest bobcamera build 1.6.3 with the multicamera support, yay! :) I haven't connected the rest of the cameras yet but I'm very happy to see that it's now possible! 

This comment is more about a technical problem (bug?) I have with the latest build - under Recording Navigation there are no listings of any recordings. It has the column names on top but no dates/recordings listed below. Do you have any idea what's the problem and how to sort it? I have my suspicions that with the multicamera support maybe there's a change in the directories but the menu is still looking in the old directory. But if that's the case I have no idea how to fix it so any help will be appreciated. 

P.S. the camera is working, detection is working, records showing clips are being saved, but nothing in the recordings page...
