### ISSUE TITLE
Include application tracking profiles

### ISSUE THREAD

**Issue by Micky-G** [bobcamera/bobcamera#29]
High Sensitivity - Small and Fast moving target Insect/Bird
Medium Sensitivity Drone/Small Plane
Low Sensitivity - Large slow moving - Commercial plane.

This might be useful: [Motion Configuration Setup](https://motion-project.github.io/motion_config.html)

**Comment by jdmaudio** [comment]
Here's an example of one of their motion.conf files for note:

https://github.com/Motion-Project/motion/blob/master/data/motion-dist.conf.in

**Comment by Micky-G** [comment]
@jdmaudio is this issue resolved now at least for v1?

**Comment by Micky-G** [comment]
I think this issue can be marked as resolved for v1.
