### ISSUE TITLE
RTSP Support

### ISSUE THREAD

**Issue by katlol** [bobcamera/bobcamera#3]
[
8:39 PM
]
ng_xyz
:
@David wanted to make our Bob multilingual so he is able to talk to all security cameras via popular protocols

**Comment by katlol** [comment]
https://github.com/mpromonet/v4l2rtspserver

**Comment by Micky-G** [comment]
@katlol is this still an issue or is it closed now as we support RTSP?

**Comment by katlol** [comment]
nope, closed as solved

**Comment by Micky-G** [comment]
Need a place to store [this repository](https://github.com/fkie/rtsp_image_transport).

**Comment by katlol** [comment]
You should be able to fork it in the bob GitHub org

**Comment by Micky-G** [comment]
Thanks @katlol just need to figure out what it is first and see if it has value to us 😜
