### ISSUE TITLE
Masking / ROI

### ISSUE THREAD

**Issue by Micky-G** [bobcamera/bobcamera#30]
We need to implement Masking and or ROI

After Dan's video showing the example Mask being created using his web GUI, this made me think of a couple of items.

We need a Web Service package/component that is the main interaction point for @danlohman's Web UI. This should also abstract away the application internals from the Web UI as its interaction should be only with the services located at this level. This Web Service component can be launched using the ROS bridge or display launch file, actually these probably need to integrated into a single UI type launch file versus being separate. @Micky-G TODO this.

My suggestion would be that we have a Mask Updater service in this Web Service component that will take an updated image from the Web UI. It will then persist the image in a known location. The making applying operation should be located in the image processing component as its a kernel level operation and it will receive the name of the mask file as part of a start up parameter.

I think we need two parameters for the making operation:

1. Mask file name
2. Mask edit mode

The reason for the 2nd parameter is because I suspect the mask will be loaded and then cached for the remainder of the time. This component will need to know if the mask has been updated so that it can be loaded again from file. So while the masking operation is in edit mode, the file should be read from disk e.g. every frame or every second, so that the end user can fine tune the mask. When editing is complete, the mask image file can be loaded and cached until otherwise notified i.e. the next time the mask is edited.

**Comment by jdmaudio** [comment]
What's the plan of attack with this for v1?  How about taking the approach they do in motion project?
https://motion-project.github.io/4.4.0/motion_config.html#mask_file

Specifically-
1) Export single frame as image
2) From this user creates mask in image editor (e.g. GIMP) and saves as .pgm (Portable GrayMap)
3) Read in mask file and then mask frames using a bitwise AND

**Comment by jdmaudio** [comment]
Some info on how they do a privacy mask which will need to be included as well as the BGS mask: 
https://motion-project.github.io/4.4.0/motion_config.html#mask_privacy

**Comment by Micky-G** [comment]
@jdmaudio @danlohman I have added a bob_webapi package and at the moment it contains a mask_webapi_node. The idea here is that this will be the node the web page calls to update the mask. At the moment it stores it in a masks folder in the webapi package, but this can change to a central repository folder or whatever we decide. The MaskUpdate service end point at **bob/webapi/mask/update** requires a message looking like this:

```
string file_name
sensor_msgs/Image mask
---
bool success
string message # information, e.g. error message
```
It's fairly self explanatory, would you see if you can try and call it from the mask creator page and then see if it writes a mask to (I think): ```/workspaces/bobcamera/src/ros2/install/bob_webapi/share/bob_webapi/masks```. This folder location needs to change but just want to see if we can get it working at the moment.

**Comment by jdmaudio** [comment]
@Micky-G @danlohman I had a shot at this and managed to get it working, see 336e1e0

Any comment appreciated

**Comment by Micky-G** [comment]
Awesome @jdmaudio how do we run the web component, do you guys build the container and then run it? Do you by any chance have the commands for that and then I will include it in the ReadMe.
