### ISSUE TITLE
Rosbag Recording and Playback

### ISSUE THREAD

**Issue by Micky-G** [bobcamera/bobcamera#31]
Use Rosbag for the recording mechanism. The python code just needs to be converted to C++.

Highly correlated to application tracking profile
To be defined still

**Comment by Micky-G** [comment]
I have found [this example](https://docs.ros.org/en/iron/Tutorials/Advanced/Recording-A-Bag-From-Your-Own-Node-CPP.html) so I might have a stab at this later.

**Comment by jdmaudio** [comment]
Once we determine the criteria for when an event should be recorded, we should probably have a parameter to determine the time length of data recorded pre and post event?

**Comment by Micky-G** [comment]
I am going to move this issue to v2, we can use the video recordings for v1.
