### ISSUE TITLE
Start exploring ONVIF for PTZ control

### ISSUE THREAD

**Issue by Micky-G** [bobcamera/bobcamera#38]
Hey @ngxyzaudax this is just an open task to ask if you would like to start exploring the ONVIF protocol and how best to use it to control a PTZ camera. Its something we are going to want to integrate eventually anyway, so if you have scope to try and explore some of it, that would be awesome!

**Comment by ngxyzaudax** [comment]
Yes! I would very much like to do that, i have Dahua SD5A445GB-HNR right next to me, i was planning to do that. There are few mechanical things that can be controlled using ONVIF protocol that i will try to explore.

- Mechanical Iris
- Focus
- Pan, Tilt and Zoom

So far was reading data FROM camera to gather basic info such as hostname, DHCP settings, and video stream configuration.

**Comment by jdmaudio** [comment]
Eventually maybe it would be good for us to model some scenarios for PTZ tracking? E.g. for a camera with a certain capability in terms steering and zoom, can we reliably follow the predicted centre point of an object with x velocity in pixel space?

Given the wide variety of camera types a user could have, perhaps there is a calibration or config stage we could introduce to determine what the upper bound is on what can be tracked

**Comment by jdmaudio** [comment]
Closing as this has been progressed sufficiently - see onvif service and bob_ptz
