### ISSUE TITLE
Resolve merge conflicts for Simulation PR

### ISSUE THREAD

**Issue by Micky-G** [bobcamera/bobcamera#43]
Hi David, would you mind looking into this merge conflict please?

For **launch_application.sh** I think I would go with line 4 versus line 13, everything else from main should be okay.
For **background_subtractor.cpp** I would just pick the changes from from main and move those params into the launch file.

These are just pointers, just shout if I can help in anyway.

**Comment by jdmaudio** [comment]
This has now been addressed and merged into main. Parameters in background_subtractor.cpp now accessible through env variables in launch script
