### ISSUE TITLE
Include additonal data in tracking state

### ISSUE THREAD

**Issue by Micky-G** [bobcamera/bobcamera#47]
I think there is some additional data that needs to be included in the tracking state message.

- FPS
- BGS being used
- Tracker being used

Do we need bgs and tracking parameters as well?

This will then all be captured as part of the message in RosBag which should allow us to inspect track details if we need to for tuning. Alternatively we create a new message called tracking args or application args or something.

@fcbarros what are your thoughts on this please?

**Comment by jdmaudio** [comment]
Would this be the right place to record:
- Cam resolution
- Local time, location (if we have a gps, or IP Address Geolocation IDK)
- rtsp or usb etc

**Comment by Micky-G** [comment]
That is a fair point, I don't quite know the answer to this but maybe some of this can be part of the observation node. I don't know where to draw the line, that is probably something we need to decide at some point.

**Comment by ngxyzaudax** [comment]
I think this meta info is really important in terms of machine learning efforts. For example i was thinking about producing bunch of crops from recorded videos so i can train all kinds of models such as self-supervised clustering model or classifiers. Shortly after i realized that dataset versioning will be challenge in its own. Raw videos are only constant here and everything else changes. Version of BOB changes resulting in different crops being produced from version to version on the same input videos, even same version of BOB with slightly different processing pipeline configuration will produce different output. 

If we have such metadata like:

- camera parameters(resolution, exposure, gain, focus)
- timestamp
- station location
- pipeline parameters(what BGS algo, what threshold, Tracking algo. and tracking parameters....)


with this info we could generate ML datasets for specific cases where our models are not performing as well.

**Comment by Micky-G** [comment]
@jdmaudio I think you have been making progress on this as well with the camera details etc you have been working on?

**Comment by jdmaudio** [comment]
Yes I’ve been using the following which will supply cam info via onvif. I populate the camera info message we have setup in the bob_camera video/rtsp node. Need to demo it to you. 

https://github.com/yingchengpa/python-onvif2-zeep?tab=readme-ov-file

There is another relevant message as well (image info) which could also hold useful info from the camera e.g brightness, sharpness etc

**Comment by jdmaudio** [comment]
I also did some playing with gps and got this working: https://github.com/ros-drivers/nmea_navsat_driver

I was thinking that for each event we could record time and accurate location along with cam info and the video

**Comment by jdmaudio** [comment]
Good enough for v1
