### ISSUE TITLE
How to deal with a tracker malfunction (too many tracks)?

### ISSUE THREAD

**Issue by Micky-G** [bobcamera/bobcamera#48]
So this issue has come about due to the tracker trying to track blue sky bits as the clouds were moving past.
This caused the tracker to go a little nuts, I captured some of the video so that we can use it for testing.

One suggestion might be if we are tracking 20 or so tracks we know the track and bgs settings might be a little too sensitive so we need to switch to a less sensitive setting, or we disable tracking for 5 or 10 minutes. Do we then revert to a higher sensitivity when things settle down? This is probably a good time to consider auto tuning between the three profiles tracking profiles as well.

Anyway this issue is here just so that we can come up with a bit of a solution for it and also to track it.

**Comment by Micky-G** [comment]
## Example tracking profiles

### Low sensitivity:

``` 
export BOB_VIBE_PARAMS=${BOB_VIBE_PARAMS:-"{\"threshold\": 65, \"bgSamples\": 32, \"requiredBGSamples\": 2, \"learningRate\": 4}"} 
export BOB_WMV_PARAMS=${BOB_WMV_PARAMS:-"{\"enableWeight\": true, \"enableThreshold\": true, \"threshold\": 55.0, \"weight1\": 0.5, \"weight2\": 0.3, \"weight3\": 0.2}"} 
export BOB_BLOB_PARAMS=${BOB_BLOB_PARAMS:-"{\"sizeThreshold\": 10, \"areaThreshold\": 100, \"minDistance\": 100, \"maxBlobs\": 100}"}
```

### Medium sensitivity:
 
```
export BOB_VIBE_PARAMS=${BOB_VIBE_PARAMS:-"{\"threshold\": 50, \"bgSamples\": 16, \"requiredBGSamples\": 2, \"learningRate\": 4}"} 
export BOB_WMV_PARAMS=${BOB_WMV_PARAMS:-"{\"enableWeight\": true, \"enableThreshold\": true, \"threshold\": 40.0, \"weight1\": 0.5, \"weight2\": 0.3, \"weight3\": 0.2}"} 
export BOB_BLOB_PARAMS=${BOB_BLOB_PARAMS:-"{\"sizeThreshold\": 6, \"areaThreshold\": 36, \"minDistance\": 36, \"maxBlobs\": 100}"}
```

### High sensitivity:

``` 
export BOB_VIBE_PARAMS=${BOB_VIBE_PARAMS:-"{\"threshold\": 35, \"bgSamples\": 16, \"requiredBGSamples\": 2, \"learningRate\": 4}"} 
export BOB_WMV_PARAMS=${BOB_WMV_PARAMS:-"{\"enableWeight\": true, \"enableThreshold\": true, \"threshold\": 25.0, \"weight1\": 0.5, \"weight2\": 0.3, \"weight3\": 0.2}"} 
export BOB_BLOB_PARAMS=${BOB_BLOB_PARAMS:-"{\"sizeThreshold\": 2, \"areaThreshold\": 4, \"minDistance\": 4, \"maxBlobs\": 100}"}
```

**Comment by jdmaudio** [comment]
Sunlight through partial cloud is the killer IMO. We could use the cloud estimator to drive a switch between the sensitivity profiles? Clear blue sky or fully overcast could probably just work on high sensitivity. 

The above settings seem a good starting point.

**Comment by jdmaudio** [comment]
Introduced another level of sensitivity 'minimal' and adjusted settings across all levels.  

The effectiveness of parameters set for one resolution may not directly translate to another resolution due to the inherent difference in pixel counts and representation of details.  This will impact blob detection in particular.  Might be worth having a scaling function or something to adjust sensitivity params based on resolution of the cam

**Comment by Micky-G** [comment]
For v1.1 look at getting this info from the blob detector versus the tracking state

**Comment by Micky-G** [comment]
Agreed on 2023.10.14 that we can close this issue for now
