### ISSUE TITLE
Event recording representation 

### ISSUE THREAD

**Issue by jdmaudio** [bobcamera/bobcamera#52]
We're exploring different methods for representing video events to give the user a quick indication of what has been recorded. Some proposed approaches include:

- Capturing the frame with the highest motion as determined by counting pixels in the BGS foreground mask.
- Developing a 'path' or 'trajectory' visualization by overlaying object positions over the entire duration of its track on a single image.
- Keogram as detailed in [allsky's documentation](https://github.com/thomasjacquin/allsky#keograms) although this is likely more suited to astro cam applications
- Heatmap view

We also need to think about when this representation will be generated e.g. directly after the event, or in a batch at the end of the day? 

Additional suggestions or techniques that can further improve video event representation capabilities welcome.

**Comment by jdmaudio** [comment]
Some initial work done on heatmap generation (shown below). This approach takes the absolute difference between consecutive frames in a region of interest determined by a mask. This accumulated over the length of the entire video then overlaid onto the frame of maximum motion.

![drone_heatmap](https://github.com/bobcamera/bobcamera/assets/2994774/b8b913fc-7725-46a0-9a99-ef337b456e12)
![plane_heatmap](https://github.com/bobcamera/bobcamera/assets/2994774/a001c654-bb5f-4aef-9737-e855bd78d6af)
![geese_heatmap](https://github.com/bobcamera/bobcamera/assets/2994774/f9a5efce-946d-4541-a075-bc5ae55cdf0e)

**Comment by Micky-G** [comment]
I think the heat maps are good enough for v1, so going to close this issue for now.
