### ISSUE TITLE
Docker Container with Web Server Needed to Run the Web GUI Subfolder

### ISSUE THREAD

**Issue by danlohman** [bobcamera/bobcamera#8]
The web gui subfolder needs a .devcontainer directory containing a devcontainer.json file and a Dockerfile in order to launch a web server for the web GUI. Also, feel free to rearrange the file paths if it is needed.  Ideally we can add php to this docker container.  If there are difficulties doing so, I can convert the proxy.php file to python or some other server side scripting language. The 3d-adsb.php file is actually just html but it uses the proxy.php file, so I made it a php file instead of html to make that obvious.  It can be renamed with a html extension if the proxy.php file is converted from php.

**Comment by katlol** [comment]
#18

**Comment by MikeGroenewald** [comment]
@katlol @danlohman I assume this issue is done? Could it be closed?

**Comment by Micky-G** [comment]
@danlohman @katlol hey guys, just checking to see if this issue can be closed?

**Comment by katlol** [comment]
closed as solved
