### ISSUE TITLE
Event Track Data

### ISSUE THREAD

**Issue by Micky-G** [bobcamera/bobcamera#92]
For every track we need a 
- unique identifier
  - camera id
  - track id
  - time

- co ordinates
  - x
  - y

Folder structure
- Continuous recording

**Comment by jdmaudio** [comment]
I think the new jsonrecorder addresses this to some extent, see [here ](https://github.com/bobcamera/bobcamera/commit/2e77589a1e79806d130f7e20ca935eb81a021eb4)

**Comment by Micky-G** [comment]
@jdmaudio I agree, do you think we close this issue as its good enough for v1?

**Comment by Micky-G** [comment]
Issue closed as good enough for v1
