### ISSUE TITLE
Detection and Privacy Mask

### ISSUE THREAD

**Issue by Micky-G** [bobcamera/bobcamera#93]
At the moment, we have the concept of a detection mask but not a privacy mask.

I think maybe for v1 if we go with a single mask solution as both the detection and privacy mask and then in v2 we look to separate these out and apply them independently of each other?

So for the moment, the detection mask should be applied to the camera feed as a privacy mask as well.

**Comment by jdmaudio** [comment]
Seems like use of a single mask for both would be an easy thing to do in practice.  Just a switch of topics in the AnnotatedFrameProvider and VideoRecorder (through app_config) I think?

**Comment by jdmaudio** [comment]
Masked frames go out by MaskApplication node using  'bob/camera/all_sky/bayer_masked'

**Comment by jdmaudio** [comment]
May as well I think @Micky-G Seems like a little one we could tick off. Thanks

**Comment by Micky-G** [comment]
This is task has been completed for v1
